# Generated by Django 5.0 on 2023-12-27 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of product', max_length=150, verbose_name='Наименование товара')),
                ('model', models.CharField(help_text='Model of product', max_length=150, verbose_name='Модель продукта')),
                ('date_of_release', models.DateField(help_text='Date of release', verbose_name='Дата выхода продукта на рынок')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
