# Generated by Django 5.0 on 2023-12-27 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the organization', max_length=150, verbose_name='Название организации')),
                ('email', models.EmailField(help_text='example@mail.com, 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=254, verbose_name='Email-адрес')),
                ('postcode', models.PositiveIntegerField(help_text='Postcode, Example:08860', verbose_name='Почтовый индекс')),
                ('country', models.CharField(help_text='County, Example:Spain', max_length=50, verbose_name='Страна')),
                ('city', models.CharField(help_text='City, Example:Barcelona', max_length=50, verbose_name='Город')),
                ('street', models.CharField(help_text='Street, Example:Passeig Maritim', max_length=100, verbose_name='Улица')),
                ('house', models.CharField(help_text='House, Example:11', max_length=10, verbose_name='Дом')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TradingNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_type', models.IntegerField(choices=[(0, 'Factory'), (1, 'Retail network'), (2, 'Individual entrepreneur')], verbose_name='Тип организации')),
                ('debit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Задолженность перед поставщиком')),
                ('contacts', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts_organization', to='trading_network.organization', verbose_name='Контакты')),
                ('products', models.ManyToManyField(to='product.product', verbose_name='Продукты')),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_supplier', to='trading_network.tradingnetwork', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Торговая сеть',
                'verbose_name_plural': 'Торговые сети',
                'ordering': ['pk'],
            },
        ),
    ]
