# Generated by Django 5.0 on 2024-01-05 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_network', '0002_alter_tradingnetwork_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='city',
            field=models.CharField(help_text='City, Example: Barcelona', max_length=50, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='country',
            field=models.CharField(help_text='County, Example: Spain', max_length=50, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='house',
            field=models.CharField(help_text='House, Example: 11', max_length=10, verbose_name='Дом'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='postcode',
            field=models.PositiveIntegerField(help_text='Postcode, Example: 08860', verbose_name='Почтовый индекс'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='street',
            field=models.CharField(help_text='Street, Example: Passeig Maritim', max_length=100, verbose_name='Улица'),
        ),
        migrations.AlterField(
            model_name='tradingnetwork',
            name='organization_type',
            field=models.IntegerField(choices=[('0', 'Factory'), ('1', 'Retail network'), ('2', 'Individual entrepreneur')], verbose_name='Тип организации'),
        ),
    ]
