# Generated by Django 5.0 on 2024-01-05 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_network', '0003_alter_organization_city_alter_organization_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradingnetwork',
            name='organization_type',
            field=models.IntegerField(choices=[(0, 'Factory'), (1, 'Retail network'), (2, 'Individual entrepreneur')], verbose_name='Тип организации'),
        ),
    ]
